# Versi API untuk Secret
apiVersion: v1
# Jenis resource yang dibuat
kind: Secret
metadata:
  # Nama Secret ini
  name: mongo-secret
# Tipe Secret ini Opaque,
# yang berarti data yang disimpan tidak memiliki format atau struktur khusus
type: Opaque
data:
  # Data yang disimpan dalam Secret
  # Username MongoDB yang telah dienkripsi (base64)
  MONGO_ROOT_USERNAME: YWRtaW4=
  # Password MongoDB yang telah dienkripsi (base64)
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==