version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest-alpine
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-karsajobs:
    docker:
      - image: golang:1.15-alpine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache gcc g++ libgcc
            go mod download
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs-ui:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t ghcr.io/maoelana/a433-microservices/karsajobs-ui:v1 .
      - run:
          name: Push Docker Image to Github Container Registry
          command: |
            echo $PASSWORD_GITHUB_REGISTRY | docker login ghcr.io -u maoelana --password-stdin
            docker push ghcr.io/maoelana/a433-microservices/karsajobs-ui:v1

workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
